version: "3"
services:
  api:
    image: randize_api
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: randize_api
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
